name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean Install
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force
        continue-on-error: true

      - name: Install Dependencies 
        run: |
          # First install react and react-dom to ensure correct versions
          npm install --save react@17.0.2 react-dom@17.0.2 --legacy-peer-deps
          
          # Install Material-UI packages
          npm install --save @mui/material@5.0.0 @emotion/react@11.0.0 @emotion/styled@11.0.0 @mui/icons-material@5.0.0 @mui/styles@6.4.0 --legacy-peer-deps
          
          # Install other dependencies
          npm install --save react-router-dom@5.3.0 react-transition-group@4.4.1 --legacy-peer-deps
          
          # Install react-typist with force to handle peer dependency
          npm install --save react-typist@2.0.5 --force
          
          # Install dev dependencies
          npm install --save-dev gh-pages@6.3.0 @babel/plugin-proposal-private-property-in-object@7.21.11 eslint@8.0.0 eslint-plugin-react@7.0.0 prettier@2.2.1 --legacy-peer-deps
          
          # Install react-scripts
          npm install --save react-scripts@5.0.1 --legacy-peer-deps
        timeout-minutes: 10

      - name: Build 
        run: |
          CI=false npm run build
        timeout-minutes: 5

      - name: Deploy to GitHub Pages 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          git-config-name: GitHub Actions
          git-config-email: github-actions@github.com
          commit-message: "Deploy React app to GitHub Pages"
          single-commit: true
